Components/CartSummaryViewComponent.cs
using System;
using Indo_Burma.Models;
using Microsoft.AspNetCore.Mvc;

namespace Indo_Burma.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/CategoryViewComponent.cs
using System;
using System.Linq;
using Indo_Burma.Models;
using Microsoft.AspNetCore.Mvc;

namespace Indo_Burma.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookRepository repo { get; set; }

        public CategoryViewComponent (IBookRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {                               // need the endpoints together to do this RouteData
            ViewBag.SelectedCategory = RouteData?.Values["bookCat"];
            var cat = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return View(cat);
        }
    }
}

Views/Shared/BookDetails.cshtml
@{
}
@*Page built for the dynamic call for anypage. Called through <partial name= model=/>*@
@model Book

<div class="col-5 card card-outline-primary m-5">
    <h4>@Model.Title</h4>
    <ul class="Container">
    @*This is a form hidden as a button that passes all the necessary book info and session info*@
        <form method="post" name="AddToCart" asp-page="/Cart" style="float:right;">
            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button class="btn btn-primary">Add to Cart</button>
        </form>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>Isbn: @Model.Isbn</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li>Page Count: @Model.PageCount</li>
        <span class="badge badge-pill badge-primary p-2" style="float:right"> <b>$@(Math.Round(Model.Price,2))</b></span>
    </ul>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Indo Burma</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Indo Burma</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul style="float:right" class="navbar-nav flex-grow-1 float-right">
                        <li class="nav-item">
                            @*Pulls in the cart and information summaries with icon(see components>CartSummaryViewComponent.cs)*@
                            <vc:cart-summary/>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div name="links" class="col-2 bg-secondary bg-gradient text-white">
            @* A connection to the View Components file where a list of book categories is built*@
           <vc:category/>
        </div>
        <div class="col-10">
            @RenderBody()
        </div>
    </div>

    <!--<footer class="border-top footer text-muted">-->
        @*<div class="container">
            &copy; 2022 - Indo Burma
        </div>*@
    <!--</footer>-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>